### ISSUE TITLE
Install location of syclcc.json -> /etc/syclcc.json?

### ISSUE THREAD

**Issue by justxi** [illuhad/hipSYCL#121]
Installing hipSYCL to e.g. "/usr/local/" results in Gentoo Linux complaining about this as a non standard location. If I install to /usr, then syclcc.json would go to /usr/etc. Which I think is also not the desired location. Is it possible to install to "/etc/syclcc.json" in general?

**Comment by illuhad** [comment]
not yet. hipSYCL is at the moment designed to be fully prefixed at install, in order to make it easy to install different variants (which would be the typical use case on a cluster, for example). I can see that it would be "nice" to have the config file in `/etc/` for system-wide installations, but I'm not sure how to best implement this.

**Comment by illuhad** [comment]
I would recommend installing hipSYCL to e.g. `/opt/hipSYCL`. Is this an option on Gentoo?

**Comment by justxi** [comment]
> I would recommend installing hipSYCL to e.g. `/opt/hipSYCL`. Is this an option on Gentoo?
No.

But he syclcc.json could be searched like you do it now and if there is no config file in that path, /etc/syclcc.json could be a "fallback".

**Comment by justxi** [comment]
There is "SYSCONFDIR", maybe you could overwrite it with your path?

https://cmake.org/cmake/help/v3.15/module/GNUInstallDirs.html

**Comment by illuhad** [comment]
Please check if PR #123 does the trick.

**Comment by justxi** [comment]
Looks good.

**Comment by illuhad** [comment]
Implemented in PR #123

**Comment by justxi** [comment]
Thanks you, I make use of it already in the latest ebuild.
There are some more complaints about the library path, see "src_prepare", what I have changed.

https://github.com/justxi/rocm/blob/eebef7831dd25f1ae752ee0d47c554cea36e3ddf/sys-devel/hipSYCL/hipSYCL-9999.ebuild#L48

But we can change that later. I tested it successfully on my nVidia system. 
The ROCm system will follow.
