### ISSUE TITLE
ROCM Build, without CUDA, syclcc-clang wants --hipsycl-cuda-path defined

### ISSUE THREAD

**Issue by dwdoerf** [illuhad/hipSYCL#150]
I'm trying to do a build on a platform with just an AMD GPU, and no CUDA installation. In the make process a test of syclcc-clang errors because --hipsycl-cuda-path is not defined:

lyra-login1:build-rocm$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/hipSYCL ../
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No suitable LLVM 10 installation found.
-- Building hipSYCL against LLVM configured from /ccs/home/dwdoerf2/opt/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/cmake/llvm
-- Selecting clang: /ccs/home/dwdoerf2/opt/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang++
-- Using clang include directory: /ccs/home/dwdoerf2/opt/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/clang/9.0.0/include
-- Configuring done
-- Generating done
-- Build files have been written to: /ccs/home/dwdoerf2/src/hipSYCL/build-rocm
lyra-login1:build-rocm$ make
Scanning dependencies of target hipSYCL_cpu
[  3%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/application.cpp.o
[  7%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/device.cpp.o
[ 11%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/device_selector.cpp.o
[ 15%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/exception.cpp.o
[ 19%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/queue.cpp.o
[ 23%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/handler.cpp.o
[ 26%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/buffer.cpp.o
[ 30%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/task_graph.cpp.o
[ 34%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/accessor.cpp.o
[ 38%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/async_worker.cpp.o
[ 42%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/local_memory.cpp.o
[ 46%] Linking CXX shared library libhipSYCL_cpu.so
[ 46%] Built target hipSYCL_cpu
Scanning dependencies of target hipSYCL_rocm
[ 50%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/application.cpp.o
syclcc fatal error: Required command line argument --hipsycl-cuda-path or environment variable HIPSYCL_CUDA_PATH not specified
src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/build.make:62: recipe for target 'src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/application.cpp.o' failed
make[2]: *** [src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/application.cpp.o] Error 255
CMakeFiles/Makefile2:177: recipe for target 'src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/all' failed
make[1]: *** [src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
lyra-login1:build-rocm$

**Comment by illuhad** [comment]
Thanks for reporting. I'm currently on vacation, so I cannot provide a proper fix, but as a work around, please try setting the `HIPSYCL_CUDA_PATH` variable to some dummy value, e.g.
```
export HIPSYCL_CUDA_PATH="somewhere"
```
It's important *not* to set it to an empty string.

For hipSYCL developers: I think the issue arises because we now have support for variables like `$HIPSYCL_CUDA_PATH` inside `syclcc.json` for the cuda and rocm link line. These variables are expanded by `syclcc-clang`.
During the process of expanding, `syclcc-clang` creates a dict to map from supported variable names to values. Since one of the supported variables is the cuda path, it errors when it isn't defined.
As a solution, we could maybe ignore errors caused by missing variables during expansion, at least when errors are related to a backend that we are not interested in. Alternatively, we could generate a default `syclcc.json` with dummy values for the paths if not provided.

**Comment by dwdoerf** [comment]
OK, that did the trick. Enjoy your vacation!

**Comment by illuhad** [comment]
Reopening until root cause is fixed.

**Comment by illuhad** [comment]
I believe PR #157 resolves the issue properly - could you please verify?

**Comment by dwdoerf** [comment]
With the branch fix-issue-#150, I'm now getting an error that llvmorg-9.0.0-rc6/bin/lld doesn't exist:

lyra-login1:build-test$ cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/hipSYCL ../
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:17 (set):
  implicitly converting 'INTEGER' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- No suitable LLVM 10 installation found.
-- Building hipSYCL against LLVM configured from /ccs/home/dwdoerf2/opt/llvmorg-9.0.0-rc6/lib/cmake/llvm
-- Selecting clang: /ccs/home/dwdoerf2/opt/llvmorg-9.0.0-rc6/bin/clang++
-- Using clang include directory: /ccs/home/dwdoerf2/opt/llvmorg-9.0.0-rc6/lib/clang/9.0.0/include
-- Configuring done
-- Generating done
-- Build files have been written to: /ccs/home/dwdoerf2/src/hipSYCL/build-test
lyra-login1:build-test$ make
Scanning dependencies of target hipSYCL_cpu
[  3%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/application.cpp.o
[  7%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/device.cpp.o
[ 11%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/device_selector.cpp.o
[ 15%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/exception.cpp.o
[ 19%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/queue.cpp.o
[ 23%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/handler.cpp.o
[ 26%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/buffer.cpp.o
[ 30%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/task_graph.cpp.o
[ 34%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/accessor.cpp.o
[ 38%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/async_worker.cpp.o
[ 42%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_cpu.dir/local_memory.cpp.o
[ 46%] Linking CXX shared library libhipSYCL_cpu.so
[ 46%] Built target hipSYCL_cpu
Scanning dependencies of target hipSYCL_rocm
[ 50%] Building CXX object src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/application.cpp.o
clang-9: error: unable to execute command: Executable "/autofs/nccs-svm1_lyra/dwdoerf2/opt/llvmorg-9.0.0-rc6/bin/lld" doesn't exist!
clang-9: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/build.make:62: recipe for target 'src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/application.cpp.o' failed
make[2]: *** [src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/application.cpp.o] Error 1
CMakeFiles/Makefile2:176: recipe for target 'src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/all' failed
make[1]: *** [src/libhipSYCL/CMakeFiles/hipSYCL_rocm.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
lyra-login1:build-test$ ls ~/opt/llvmorg-9.0.0-rc6/bin
bugpoint               clang-refactor    llvm-bcanalyzer  llvm-dlltool    llvm-mc          llvm-readelf     obj2yaml
c-index-test           clang-rename      llvm-c-test      llvm-dwarfdump  llvm-mca         llvm-readobj     opt
clang                  clang-scan-deps   llvm-cat         llvm-dwp        llvm-modextract  llvm-rtdyld      sancov
clang++                diagtool          llvm-cfi-verify  llvm-elfabi     llvm-mt          llvm-size        sanstats
clang-9                dsymutil          llvm-config      llvm-exegesis   llvm-nm          llvm-split       scan-build
clang-check            git-clang-format  llvm-cov         llvm-extract    llvm-objcopy     llvm-stress      scan-view
clang-cl               hmaptool          llvm-cvtres      llvm-jitlink    llvm-objdump     llvm-strings     verify-uselistorder
clang-cpp              llc               llvm-cxxdump     llvm-lib        llvm-opt-report  llvm-strip       yaml2obj
clang-extdef-mapping   lli               llvm-cxxfilt     llvm-link       llvm-pdbutil     llvm-symbolizer
clang-format           llvm-addr2line    llvm-cxxmap      llvm-lipo       llvm-profdata    llvm-tblgen
clang-import-test      llvm-ar           llvm-diff        llvm-lto        llvm-ranlib      llvm-undname
clang-offload-bundler  llvm-as           llvm-dis         llvm-lto2       llvm-rc          llvm-xray

**Comment by illuhad** [comment]
I think this may be unrelated to the PR. It seems your are now using a different LLVM installation, one which does not have `lld` available as seen from your `ls` output. The clang amdgpu backend requires `lld` (this is a general requirement of ROCm when compiling HIP code with clang, and independent of hipSYCL).
Have you compiled this llvm from source? If I remember correctly, there's a cmake variable in llvm where you can specify which LLVM subprojects to enable. lld must be enabled there. Additionally, assertions must be disabled.
You may be interested in our llvm installation script in `install/scripts/install-llvm.sh`. It clones llvm git master by default (llvm 10), but you could also change this to llvm 9 branch as you currently use.

**Comment by dwdoerf** [comment]
OK, I seem to have figured things out. I've done as you suggest and followed your install-llvm.sh for a fresh build of llvm (master branch) and install-hipsycl.sh. This was all done with the branch "fix-issue-#150". I've run some simple tests and the build for room and cpu are working!

FYI, the machine I'm using has ROCM version 2.9. So in install-hipsycl.sh I had to remove the references to -lamd_hostcall and -latmi_runtime. I assume these were part of earlier releases? But in 2.9 they no longer seem to exist. 

Thanks for your help!

**Comment by illuhad** [comment]
Great to hear it's now working! I'll merge that branch momentarily.

The ROCm link line in `install-hipsycl.sh` is tailored to the specific ROCm distribution that we package (as installed by `install-rocm.sh`). This script installs ROCm from source and is based on the AMD aomp installation scripts. With aomp, I noticed that these libraries must be linked additionally instead of just `-lhip_hcc`. These libraries are also not required for earlier ROCm releases as in the binary packages from AMD. So, I suspect that this is not because of different ROCm versions, but instead probably because AMD chose to link all libraries statically in their binary packages such that everything is contained in `-lhip_hcc`. When compiling from source, this apparently doesn't automatically happen, and we therefore need the additional linker arguments.

Thank you for your feedback!
