### ISSUE TITLE
Create proper package repositories

### ISSUE THREAD

**Issue by illuhad** [illuhad/hipSYCL#153]
We should create proper repositories for our supported distributions, so that users can simply enable those repositories and install hipSYCL using their package manager (and keep it updated).

A mechanism is also needed to
* update hipSYCL packages regularly (e.g., each day build a new package from master branch)
* update hipSYCL llvm/base packages in a more coarse interval (e.g., every month).

**Comment by illuhad** [comment]
Virtual machines are approved and will be available within one or two days. @sbalint98, as soon as the VMs are here, this should be priority.

**Comment by sbalint98** [comment]
I think with the new branch structure we should have the following pkg repos available:

 repo name  | branch     | update interval               | 
|------------|------------|-------------------------------|
| develop    | develop    | daily                         | 
| stable     | master     | after merging develop branch  | 
| sycl/1.2.1 | sycl/1.2.1 | after new commit or daily?             |
