### ISSUE TITLE
Implement SYCL 2020 provisional USM feature

### ISSUE THREAD

**Issue by illuhad** [illuhad/hipSYCL#155]
Intel's [unified shared memory extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/USM/USM.adoc) provides an alternative, valuable way of managing data in SYCL. We should also implement this in hipSYCL by means of CUDA/HIP unified memory. Note: In HIP, managed memory is still very new and may be bugged.

**Comment by jon-chuang** [comment]
I am quite interested in this project. I will have to study the SYCL standard closely and think about how to expose HIP unified memory. 

I should also study the Intel implementation:
https://github.com/intel/llvm/tree/sycl/sycl/source/detail/usm
https://github.com/intel/llvm/blob/sycl/sycl/include/CL/sycl/usm

**Comment by illuhad** [comment]
Hi,

thank you for your interest :) In order to implement USM in hipSYCL, you would need to develop against the API of the new runtime that is currently in development. In principle, the [hip_allocator](https://github.com/illuhad/hipSYCL/blob/scheduling-rework/include/CL/sycl/detail/scheduling/hip/hip_allocator.hpp) implementation just needs to implement the `allocate_usm` member function and map it to `hipMallocManaged()` which exists in newer HIP versions.
This function can then be exposed with the memory management functions from Intel's API.

The explicit dependency part from the Intel API with `cgh.depends_on()` is a bit more complicated as it depends even more on the new, not yet finished runtime/scheduler. I would suggest to first start with the memory management functions.

Be advised that, on AMD GPUs, `hipMallocManaged` is not expected to yield good performance as AMD implements it with zero-copying instead of on-demand page migration.

**Comment by bd4** [comment]
USM also includes `sycl::malloc_device` => `hipMalloc`, which is also very useful for using SYCL incrementally in legacy codes. That is perhaps another even simpler place to start.

**Comment by bd4** [comment]
@jon-chuang have you started work on this?

**Comment by jon-chuang** [comment]
Hi, unfortunately I am occupied with other things now. Feel free to work on this :)

**Comment by illuhad** [comment]
Again, it might be worth to be patient for some more time.. As I've said implementing USM would touch on parts of hipSYCL that are rapidly changing at the moment. USM *will* come at least before the end of the year, but probably much earlier than that :)

**Comment by jeffhammond** [comment]
I propose to rename this issue "SYCL 2020 provisional specification USM feature" 😉

**Comment by illuhad** [comment]
@jeffhammond done ;)

**Comment by keryell** [comment]
> @jeffhammond done ;)

Ah, I thought the implementation was done! But it is only the title change... :-)

**Comment by illuhad** [comment]
Just noticed that this is still open. Support for USM has been merged some time ago and is part of the 0.9 release.
