### ISSUE TITLE
Reverse mapping of SYCL work item indices to HIP/CUDA dimensions

### ISSUE THREAD

**Issue by illuhad** [illuhad/hipSYCL#158]
Currently, we map:
* id.get(0) -> hipThreadIdx_x
* id.get(1) -> hipThreadIdx_y
* id.get(2) -> hipThreadIdx_z

This is problematic, because it is inconsistent with linear ids as required by the spec. In SYCL, linear ids use the highest dimension as fastest index. This affects not only linear ids themselves but also statements like `accessor[id]` where a linear id is internally used.
In HIP/CUDA on the other hand, the x dimension (or dimension 0, in OpenCL terminology) is assumed to be the fastest moving index. As coalescing of memory accesses happens along the x dimensions, accessing multi-dimensional memory buffers the way SYCL expects it will yield suboptimal performance.

To reconcile the SYCL world and the HIP/CUDA world, we should change the mapping such that
* 1D case:
  * id.get(0) -> hipThreadIdx_x
* 2D case:
  * id.get(0) -> hipThreadIdx_y
  * id.get(1) -> hipThreadIdx_x
* 3D case:
  * id.get(0) -> hipThreadIdx_z
  * id.get(1) -> hipThreadIdx_y
  * id.get(2) -> hipThreadIdx_x

This should be fixed ASAP as the current implementation is arguably a performance bug.

**Comment by keryell** [comment]
We are using heterogeneous computing for compute performance and power efficiency... so this is important!

**Comment by illuhad** [comment]
Indeed. I have done most of the performance testing with 1D benchmarks up to now which is probably how this could have gone unnoticed. This is top priority, I have already started working on a fix right after I learned of the issue today afternoon - hopefully this will be fixed in the next few days.
