### ISSUE TITLE
HIPSYCL_GPU_ARCH not specified

### ISSUE THREAD

**Issue by Alkeryn** [illuhad/hipSYCL#171]
When trying to build some sycl code with cuda it says the gpu arch is not specified but there is literally no documentation on what to set that variable to

**Comment by Alkeryn** [comment]
Nevermind, for other people needing it you can find documentation here
https://llvm.org/docs/CompileCudaWithLLVM.html
it isn't hipsycl specific but clang and cuda specific ^

**Comment by illuhad** [comment]
... there is also some explanation/example setting mentioned in the documentation for the cmake variable `DEFAULT_GPU_ARCH` (can be seen e.g. when using `ccmake`). Maybe we should also add some example to the `syclcc --help` output.

**Comment by Alkeryn** [comment]
@illuhad The issue is that not all sycl devs are former cuda devs
so some of them might be confused by that flag other than that it is pretty great software, thanks ^

**Comment by illuhad** [comment]
Yes, I understand. I think we can also expect this to become a more frequent issue as SYCL gets more popular and we get more users who learn SYCL as their first heterogeneous programming model. So, if you'd like to add some documentation to the readme, I will happily merge a PR :)

**Comment by jeffhammond** [comment]
Yeah, more docs are required here.  I couldn't figure it out until I found this issue and read the LLVM page.  And it's not like I don't know how to use CUDA.  I guessed `sm60` but had to read the LLVM docs to figure out that I should have used `sm_60`.  That's the sort of thing that needs to be documented with `syclcc-clang --help`.

**Comment by illuhad** [comment]
@jeffhammond done, see PR #225 :)
