### ISSUE TITLE
index.get(x) dosen't work

### ISSUE THREAD

**Issue by Alkeryn** [illuhad/hipSYCL#179]
so in the code bellow : 
```cpp
    cl::sycl::buffer<size_t,1> structbuff(cl::sycl::range<1>((size_t)buffsize));
	queue.submit([&](cl::sycl::handler& cgh) {
		auto A = structbuff.get_access<access::mode::read_write>(cgh);
		cgh.parallel_for<class first>(numOfItems, [=](cl::sycl::id<1> index) {
			A[index] = index.get(1);
		});
        );

```
dosen't work, index.get(dimension); always get replaced with 0 which is quite annoying

**Comment by illuhad** [comment]
So, you're in 1D, which means the only valid index is 0. Accessing index 1 is an out-of-bounds access, which in SYCL 1.2.1 is undefined behavior.
Does it work correctly with `index.get(0)`?

**Comment by Alkeryn** [comment]
@illuhad Oh my bad, thanks it works, idk i got confuse i'd have thought we should put 1  for 1D but it is 0, thanks ^

**Comment by illuhad** [comment]
Like in C++, we start our indices with 0 in SYCL :)

**Comment by Alkeryn** [comment]
I know it for an array but i wouldn't have expected it for "the number of dimension" ^
got confused by range<1> but get(0) tldr ^
anyway thanks for the help :)
