### ISSUE TITLE
Build with LLVM 10 is broken

### ISSUE THREAD

**Issue by jon-chuang** [illuhad/hipSYCL#187]
Build system is unable to find libdevice

**Comment by fodinabor** [comment]
Please provide some extra information including your operating system and CUDA (?) version.

**Comment by illuhad** [comment]
Also please specify how you have installed CUDA. This error is usually not hipSYCL specific but indicates that CUDA compilation with clang is not correctly set up. You may be interested in [the relevant clang documentation](http://llvm.org/docs/CompileCudaWithLLVM.html#id3).

**Comment by jon-chuang** [comment]
Sorry, I am mistaken, this was a different error, it was an error I faced earlier but resolved only by building with LLVM 9. 

However, I was spending the whole day fighting errors, so I can't for the life of me remember what the problem was. Anyway, I'll close for now
