### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by jon-chuang** [illuhad/hipSYCL#188]
Ubuntu 18.04, LLVM/Clang 9, CUDA toolkit 10.0, hipSYCL latest build

Error from the commands
```
./main
bash: ./main: cannot execute binary file: Exec format error
```

From the compilation

`/usr/local/bin/syclcc-clang --hipsycl-gpu-arch=sm_61 --cuda-path=/usr/local/cuda-10.0 -o main -c main.cpp`

Which produces no errors.

However, my CUDA driver is 10.2. I had to install CUDA toolkit 10.0 as Clang apparently does not support CUDA 10.2. I suppose this is the problem.

**Comment by illuhad** [comment]
Well... you have added `-c`, so main is not linked. You will see a similar behavior with other, regular C++ compilers as well.

**Comment by illuhad** [comment]
Also, do not use `--cuda-path` unless you know have very specific reason to do so. `syclcc` automatically supplies `--cuda-path` pointing to the CUDA installation that hipSYCL was compiled against. Potentially compiling a program against a different cuda version than hipSYCL was built with is most likely not going to end well.

**Comment by jon-chuang** [comment]
Ok, the need to include the flag went away when I recompiled with `-DCUDA_TOOLKIT_ROOT_DIR`.

Sorry, I have been using CMake too much I think. 

Compiled code works. It's a work of beauty! I am so excited to dig deeper into SYCL :)

**Comment by illuhad** [comment]
Awesome, great to hear it works :)
