### ISSUE TITLE
Possibility of compilation to webGL?

### ISSUE THREAD

**Issue by jon-chuang** [illuhad/hipSYCL#195]
Can SYCL also be used to generate WebAssembly and WebGPU that are already tightly integrated in a single binary?

**Comment by jon-chuang** [comment]
If not, could someone give an estimate as to how complicated it would be to go from the IR to WASM/webGPU generation?

**Comment by jon-chuang** [comment]
It seems this is one area in the endpoint toolchain space that has not been covered in terms of SYCL projects. I wonder if anyone will ever work on this. I have to say that I am rather curious. This way, one can easily integrate web support for libraries maintained in C++ without experiencing significant code divergence.

**Comment by DieGoldeneEnte** [comment]
To generate WebGPU from hipSYCL you first need to be able to generate from HIP, which I think is not yet possible. It seems generation from OpenCL is possible and I found a project (hipcl) trying to support OpenCL/SPRI-V devices using the HIP-API.
I might missed or misinterpreted some parts, as I have never used WebASM/WebGPU and am new to (hip)SYCL :)

**Comment by illuhad** [comment]
It's an interesting idea. I'm not very familiar with either of those technologies, so I don't know exactly what would be involved in this.
Somehow generating the code is only half of the work, you would also need to have a compatible runtime API that a SYCL implementation could hook into. For hipSYCL this is currently HIP, for other implementations it would be OpenCL.

@DieGoldeneEnte I am highly interesting in combining hipSYCL with HipCL as this would allow us to target other devices such as Intel GPUs as well. Would you be interested in working on that? :)

**Comment by DieGoldeneEnte** [comment]
@illuhad I don't think I will work on HipCl for now, as I am still diving into nix/llvm and packaging hipSYCL. I like the idea of HipCL and am interested how it works. In case I find some interesting information I could open an issue as starting point for whoever wants to work on it.

**Comment by keryell** [comment]
> Can SYCL also be used to generate WebAssembly and WebGPU that are already tightly integrated in a single binary?

Sure! For example you could connect some LLVM back-ends and update the runtime to run on your host API. But this is a generic theoretical answer, probably outside of the scope of hipSYCL. I envision it more like an extension to https://github.com/intel/llvm/tree/sycl

**Comment by jon-chuang** [comment]
> Somehow generating the code is only half of the work, you would also need to have a compatible runtime API that a SYCL implementation could hook into.

I suppose this would be the dawnnative/wgpu-native runtimes with the following API: https://github.com/gfx-rs/wgpu/blob/master/ffi/wgpu.h

**Comment by illuhad** [comment]
Closing because out of scope for hipSYCL.
