### ISSUE TITLE
update SYCL ecosystem figure for CodePlay's DPC++ @ NVIDIA

### ISSUE THREAD

**Issue by jeffhammond** [illuhad/hipSYCL#208]
https://github.com/illuhad/hipSYCL/blob/master/doc/img/sycl-targets.png is super useful and I cite it all the time.

In lieu of https://www.codeplay.com/portal/02-03-20-codeplay-contribution-to-dpcpp-brings-sycl-support-for-nvidia-gpus and https://github.com/codeplaysoftware/sycl-for-cuda, I wonder if you will update the figure.  It might be worth renaming "clang (Intel SYCL)" to "DPC++" or something like that.

Note that I would be happy to contribute the changes to the figure but I don't have the source used to create it.

This is extremely low priority, which is why I created an issue rather than emailing you 😉

**Comment by illuhad** [comment]
Thank you for the reminder! I agree we should update that figure; I think there have been some more changes (e.g. also for ComputeCpp). Most of those changes have already been incorporated by Neil's Khronos slides, so I'll just compare our image with Neil's for alignment and to bring it to the current state.

PS: The source file is the `sycl-targets.xml` in the `doc/img` directory. This file can then be loaded into [draw.io](https://draw.io) :smile:

**Comment by keryell** [comment]
Yes this is actually superuseful.
On triSYCL for CPU there is also a TBB back-end contributed by someone from Intel.

**Comment by illuhad** [comment]
@keryell thanks, will be included! Let's hope there's enough space for everything :smile:

**Comment by keryell** [comment]
Since I need to give a presentation tomorrow, I bumped my priority queue with https://github.com/illuhad/hipSYCL/pull/218
https://draw.io is a very interesting tool! But it is not clear if the generated XML format is open-source or not. And the SVG export is not usable...

**Comment by illuhad** [comment]
@keryell I'm open to suggestions if you have better alternatives to draw.io :) For me the SVG export did work. Inkscape however did not render the SVG correctly for some reason (it says at the bottom that `viewer does not support full SVG 1.1`), but firefox and chromium do. Maybe we need to go through the pdf export to edit in inkscape?

@jeffhammond please check if you are happy with the current version.

**Comment by jeffhammond** [comment]
@illuhad Looks good to me.  Nobody is testing the Intel implementation on non-Intel hardware right now, so it is possible that it doesn't work with non-x86 CPUs, for example, but that isn't a fundamental design issue.

**Comment by illuhad** [comment]
@jeffhammond hmm, maybe I can give at least the host backend a try on my Power8 machine. Would be curious to see if it works...
