### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by mrzv** [illuhad/hipSYCL#227]
What's the correct way to measure run-times of SYCL code? If I have something simple
```
vector<int> data(...);

queue q;
{
  buffer b(data.data(), data.size());

  // computation
  q.submit(...);
}
```
How can I measure how long it takes to move data to the device, then to run the computation, and then to move data back? I.e., I want three separate times. Is there a clean way to do this?

**Comment by illuhad** [comment]
With hipSYCL you can use NVIDIA and AMD vendor profiling tools, e.g. `nvprof`. The SYCL spec also includes a queue profiling feature which will only allow you to measure kernels though and is unimplemented in hipSYCL. The restriction of only measuring kernels is because data transfers are implicit in SYCL and therefore, there's no way for the user to query them unless the explicit `copy()` functions are used.

**Comment by mrzv** [comment]
I'd be happy to use an explicit `copy`. Can you give me an idea how I'd do that in the example above?

**Comment by illuhad** [comment]
Your overall code could look something like this:

```
vector<int> data(...);
queue q;
{
  buffer b(data.size());
  // You need to force the sycl runtime to move data to the device now so that it won't be measured later
  // This can either be done with explicit `copy()` functions or a dummy kernel. With copy():
  q.wait_and_throw(); // Make sure queue is empty before measuring 
  double transfer_time1 = timer();
  q.submit([&](sycl::handler& cgh){ 
    auto acc = b.get_access<sycl::access::mode::discard_write>(cgh);
    cgh.copy(data.data(), acc);
  });
  q.wait_and_throw();
  double transfer_time2=timer();

  // computation
  double t1 = timer();
  q.submit(...);
  q.wait_and_throw()
  double t2 = timer();

  // Copy data back to host, analogously to first copy
  double transfer_time1 = timer();
  q.submit([&](sycl::handler& cgh){ 
    auto acc = b.get_access<sycl::access::mode::read>(cgh);
    cgh.copy(acc, data.data());
  });
  q.wait_and_throw();
  double transfer_time2=timer();
}
```
Note that I also have not initialized the buffer with the pointer in order to prevent it from doing the automatic write-back implicitly when it goes out of scope. This way, we can also measure the final device->host data transfer.

**Comment by illuhad** [comment]
(Also note that the measured times here may also include some small runtime overhead since you are also measuring scheduling of operations etc which will not be contained in measurements from tools such as `nvprof`)

**Comment by mrzv** [comment]
Brilliant. Thanks!

**Comment by illuhad** [comment]
Closing, this seems solved to me - reopen if this is not the case.
