### ISSUE TITLE
clang-10 unit_tests compilation error in lambda capture

### ISSUE THREAD

**Issue by sbalint98** [illuhad/hipSYCL#231]
When compiling the unit tests using the recently released clang-10 the following compile-time error is encountered:
```
/tmp/hipSYCL/tests/unit_tests.cpp:636:27: error: variable 'd' cannot be implicitly captured in a lambda with no capture-default specified
        [=](const s::item<d> item) {
                          ^
/tmp/hipSYCL/tests/unit_tests.cpp:636:28: note: while checking a default template argument used here
        [=](const s::item<d> item) {
                     ~~~~~~^
/tmp/hipSYCL/tests/unit_tests.cpp:615:18: note: 'd' declared here
  constexpr auto d = _dimensions::value;
```
LLVM has been built from source, from the branch [release/10.x](https://github.com/llvm/llvm-project/tree/release/10.x). The used binaries are available in our repo at http://repo.urz.uni-heidelberg.de/sycl/test_llvm10/

It is curious that compiling using clang-9 works fine.

**Comment by fodinabor** [comment]
not sure but it looks like that should work.. so I'd rather file a bug at LLVM's bugtracker?

**Comment by illuhad** [comment]
@sbalint98 Can you try if you can create a minimum reproducer that can be used to test this without hipSYCL? Ideally we can also have some C++ lawyer confirm if clang is indeed wrong here.

**Comment by sbalint98** [comment]
Sure! I'll have a look

**Comment by sbalint98** [comment]
Unfortunately, I was not able to create a truly minimal example. However, I was able to reproduce the error with only boost involved, but I am not able to pin down which part of the boost unit test framework is braking clang. I'll paste my "minimal" example here:
```
#include <boost/test/unit_test.hpp>
#include <boost/mpl/list_c.hpp>
#include <boost/mpl/list.hpp>
#include <boost/mpl/int.hpp>
#include <boost/mpl/front.hpp>


using test_dimensions = boost::mpl::list_c<int, 1, 2, 3>;
using test_int = boost::mpl::int_<2>;

template<typename F>
void f(F lambda) { /* ... */}
template<typename F>
void g(F lambda) { /* ... */}

template <int x, int y>
struct test_class {};

template<typename T>
class TD;

BOOST_AUTO_TEST_CASE_TEMPLATE(item_api, _dimensions, test_dimensions::type){
  using first_element = boost::mpl::front<test_dimensions>;
  //constexpr auto j = first_element::type::value; // compiles
  //constexpr auto  j = test_int::value;  // compiles
  
  constexpr auto j = _dimensions::type::value;
#ifdef DEBUG
  TD<decltype(j)> tst;
#endif
  f([&]()  {
      g([=](const test_class<j, 3> item) {});
  });
}
```
It also seems like that the mpl lists and containers are not related to the issue.

**Comment by fodinabor** [comment]
That looks like the only issue is that Clang fails to deduce the type here: ` constexpr auto j = _dimensions::type::value;`
replacing the `auto` with `int` (or `const int`, what the generated type seems to be according to the Clang 9.0 AST) makes this example compile..

Maybe the usage of the `j` is _too far away_ from its definition so that Clang is confused?

Anyway.. I'd apply the quick fix of using `const int` explicitly and report your minimal example to either Clang or Boost..

**Comment by sbalint98** [comment]
Thank you very much for investigating! I was afraid that I had missed something obvious. I am going to add your findings, and I will report it to clang and/or Boost. Should I report it to both of them? 

Can you elaborate on your Edit? I used TD only to invoke a template error, and get a list of macros and templates used. What do the two points in `TD<..>` stand for?

**Comment by fodinabor** [comment]
I think mostly Clang..

Ehm.. sure.. I edited the example to the following (simplified). note that I _fully defined_ `TD` by adding braces.
```c++
using test_dimensions = boost::mpl::list_c<int, 1, 2, 3>;

template<typename T>
class TD {};

BOOST_AUTO_TEST_CASE_TEMPLATE(item_api, _dimensions, test_dimensions::type){
  constexpr auto j = _dimensions::type::value;
  TD<decltype(j)> tst;
}
`

As this is able to instantiate `TD` it seems that the type deduction for `auto` works here and that it only fails to propagate the type through the lambda captures.
And as it works with the explicit `int` this is neither a general type deduction issue nor a pure lambda capture issue, but a type deduction issue + something with the lambdas combined ..

**Comment by sbalint98** [comment]
Ohh I see, thanks for clarifying :)

**Comment by sbalint98** [comment]
I submitted the bug report.
https://bugs.llvm.org/show_bug.cgi?id=45538

**Comment by illuhad** [comment]
Thanks!

**Comment by invexed** [comment]
Is there any reason the fix that @fodinabor suggested in https://github.com/illuhad/hipSYCL/issues/231#issuecomment-606699562 cannot be applied? Specifying the type explicitly appears to fix it for me: [https://godbolt.org/z/dvVxTk](url). I've had to use this workaround a couple of times in my own code in the context of variable template type deduction.

**Comment by illuhad** [comment]
@invexed No, I think that should work. Basically, if it works in the unit tests, it works - I don't think there are any additional difficulties to consider.
