### ISSUE TITLE
CMake: detecting syclcc-clang compile features

### ISSUE THREAD

**Issue by invexed** [illuhad/hipSYCL#237]
Hello. I'm attempting to link my hipSYCL application with a third-party CMake target that specifies a compile feature:

```target_compile_features(${PROJECT_NAME} INTERFACE cxx_std_20)```

However, I get the following error:
```
No known features for CXX compiler
"Clang"
version 9.0.1.
```

Indeed CMake reports ```-- Detecting CXX compile features - failed```. I've looked through CMake's codebase and found that the appropriate compile feature detection is done in ```.../Modules/Compiler/Clang.cmake``` but I have no idea how to do the same for ```syclcc-clang```?

**Comment by illuhad** [comment]
How are you using hipSYCL in your cmake project? Are you just setting `CMAKE_CXX_COMPILER` to `syclcc-clang`? If so, please try the "proper" hipSYCL cmake integration, i.e. `find_package(hipSYCL)`, then use the `add_sycl_to_target()` function and don't modify `CMAKE_CXX_COMPILER`. You can find an example here: https://github.com/illuhad/hipSYCL/blob/master/examples/bruteforce_nbody/CMakeLists.txt

**Comment by invexed** [comment]
I am indeed doing ```find_package(hipSYCL)``` and ```add_sycl_to_target()```, but I was also doing ```find_program(SYCLCC syclcc-clang)``` and ```set(CMAKE_CXX_COMPILER ${SYCLCC})``` etc. It seems to be working now that I've removed the latter.

Thanks for the quick reply!

**Comment by invexed** [comment]
I spoke too soon. Unfortunately I'm still getting the original error despite not setting ```CMAKE_CXX_COMPILER``` manually.

**Comment by invexed** [comment]
I've made a minimal project to reproduce the problem and now setting ```CMAKE_CXX_COMPILER``` manually seems to be compulsory. Here is my ```CMakeLists.txt``` file:

```
cmake_minimum_required(VERSION 3.5)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} /opt/hipSYCL/lib/cmake)
find_package(hipSYCL REQUIRED CONFIG PATH_SUFFIXES lib/cmake)

project(hipsycl-detect)

add_executable(test main.cpp)
add_sycl_to_target(TARGET test SOURCES main.cpp)
```

Invoking CMake with ```cmake -S . -B build -DCMAKE_PREFIX_PATH=/opt/hipSYCL``` results in

```
No CMAKE_CXX_COMPILER could be found.

Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.
```

but it succeeds if I add

```
find_program(SYCLCC syclcc-clang)
set(CMAKE_CXX_COMPILER ${SYCLCC})
```

before the project command. I've installed hipSYCL via the CentOS repo and ```install-cuda.sh``` script, inside a Docker container, but I don't think it's an installation problem as I can successfully compile hipSYCL programs (provided I set ```CMAKE_CXX_COMPILER``` manually). My CMake version is ```3.14.7```.

Now, back to the original problem. Let's add a mock header-only library to the root CMakeLists.txt above and 'link' with it

```
add_subdirectory(external)

add_executable(test main.cpp)
add_sycl_to_target(TARGET test SOURCES main.cpp)
target_link_libraries(test PRIVATE external)
```

and let's add the following CMakeLists.txt in the 'external' subdirectory

```
cmake_minimum_required(VERSION 3.5)

add_library(external INTERFACE)
target_compile_features(external INTERFACE cxx_std_20)
```

This reproduces my original error:
```
CMake Error in CMakeLists.txt:
  No known features for CXX compiler
  "Clang"
  version 9.0.1.
```

I've attached the source tree of this minimal example for convenience.
[hipsycl-detect.zip](https://github.com/illuhad/hipSYCL/files/4527879/hipsycl-detect.zip)

**Comment by illuhad** [comment]
> No CMAKE_CXX_COMPILER could be found.

I think the problem already starts there, as setting `syclcc` as `CMAKE_CXX_COMPILER` for more complex cmake projects is probably not a very good idea and I could image that it might lead to detection issues as described. I don't get this error on my Ubuntu machine, here `hipsycl-detect` configures and builds fine.
Do you have any compiler apart from hipSYCL installed on your machine? Are they in directories where cmake can find them?

**Comment by invexed** [comment]
It's a stock CentOS 7 machine, so it has gcc but not g++ installed. I must admit, I'm a little confused about why another C++ compiler is necessary; I was under the impression that ```syclcc``` compiles both the host and device code. Is that not the case, or is another C++ compiler required just to fool CMake and avoid it terminating with an error before ```syclcc``` is enabled?

I figured I could set my compiler to the ```clang++``` bundled with hipSYCL:

```
CXX=/opt/hipSYCL/llvm/bin/clang++ cmake ...
```
but it fails to find the standard library headers:

```
fatal error: 'algorithm' file not found
```
This would imply that the default ```CMAKE_CXX_COMPILER``` is indeed used to compile host code?

**Comment by invexed** [comment]
That makes perfect sense. I've had a look at hipSYCL's LLVM distribution, and it seems it doesn't include libc++. What are your thoughts about providing libc++ via your official repos, or would you rather that be left to the user?

**Comment by illuhad** [comment]
I'd like to avoid it because I'm not sure it's necessary. Does the CPU backend work? Because it *should* work with the bundled clang, and if it does, it must have a C++ standard library available. The hipSYCL or hipSYCL-base package on CentOS 7 *should* have a dependency on `devtoolset-7` in order to get access to reasonably new standard library headers.

**Comment by invexed** [comment]
That's fair enough. I haven't tried the CPU backend but I have no reason to doubt that it works. For my purposes it would be nice to have the repo install a recent libc++ version along with Clang itself, but it would be unfair to impose that on all users when it's not necessary.

Thanks again for your time. It's very much appreciated.
