### ISSUE TITLE
make install return error

### ISSUE THREAD

**Issue by mpak2** [illuhad/hipSYCL#244]
-- Up-to-date: /usr/local/include//hipSYCL/compiler/Attributes.hpp
-- Up-to-date: /usr/local/include//hipSYCL/compiler/FrontendPlugin.hpp
-- Up-to-date: /usr/local/include//hipSYCL/compiler/IR.hpp
-- Up-to-date: /usr/local/include//hipSYCL/compiler/Frontend.hpp
CMake Error at cmake_install.cmake:53 (file):
  file INSTALL cannot find
  "/home/mpak/git/bimorph/include/hipSYCL/contrib/hipCPU/include/hipCPU": No
  such file or directory.

make: *** [Makefile:74: install] Ошибка 1
mpak@mpak-H310MS2P:~/git/bimorph/include/hipSYCL/cmake$

**Comment by sbalint98** [comment]
Hi, 
It seems like to me, that you didn't clone the hipCPU repo. Could you try cloning hipSYCL using the `--recurse-submodules` flag?

**Comment by mpak2** [comment]
спасибо. ошибка не повторилась

**Comment by illuhad** [comment]
thanks, @sbalint98! It seems this issue is now solved, closing.
