### ISSUE TITLE
error example

### ISSUE THREAD

**Issue by mpak2** [illuhad/hipSYCL#247]
I compile the example project you provided examples/bruteforce_nbody and get an error. I built hipSYCL from hipSYCL repo to the sources but I get an error when I run it

/usr/bin/ld: _ZN7hipsycl4sycl6detail17host_local_memory17_static_local_memE: TLS definition in /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libhipSYCL_cpu.so section .tbss mismatches non-TLS reference in /tmp/ccjM7VSs.o
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libhipSYCL_cpu.so: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

shell returned 1

**Comment by illuhad** [comment]
How are you attempting to compile the example? I have seen this kind of issue before if there's a mismatch between the cmake cache and the platform you are targeting. I.e, from your output it can be seen that it tries to link against the CPU backend. Are you by chance trying to compile for GPU? If so, clear your build directory and rerun cmake.

**Comment by mpak2** [comment]
gcc bimorph.cpp -lstdc++ -std=c++17 -I"/opt/hipSYCL/include/" -lhipSYCL_cpu -lm -lpthread -o bimorph.x86-64 && ./bimorph.x86-64

**Comment by illuhad** [comment]
hipSYCL programs should be compiled with `syclcc`. Please use `syclcc` instead:
```
/opt/hipSYCL/bin/syclcc --hipsycl-platform=cpu -o bruteforce_nbody bruteforce_nbody.cpp
```
You can tell it to use a different OpenMP compiler if you like using `--hipsycl-cpu-cxx`, but you should make sure that this compiler is ABI compatible with the one you use to build hipSYCL. In this dockerfile hipSYCL is built with clang 8, so might also be some issue between clang and gcc.

**Comment by mpak2** [comment]
the program is assembled. But it returns an error on startup

./bruteforce_nbody: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory

**Comment by illuhad** [comment]
You need to install the LLVM OpenMP implementation, libomp, for the CPU backend if compiling with clang. By the way, those docker files are very old, it's probably a better idea to use hipSYCL with our package repositories: https://github.com/illuhad/hipSYCL/blob/master/install/scripts/README.md#installing-from-repositories

**Comment by mpak2** [comment]
thanks
