### ISSUE TITLE
USM support

### ISSUE THREAD

**Issue by paboyle** [illuhad/hipSYCL#248]
https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/USM/USM.adoc

Hi, 

are there plans to support the Intel proposed USM extensions to SYCL?

I'm trying to factor / estimate the chance of SYCL on AMD with and without SVM working in timeframe for Frontier at ORNL.

Thanks,

Major design / code decision with scientific work depending on proper planning, so advice appreciated.

**Comment by fodinabor** [comment]
Have a look at #155 for the current status

**Comment by illuhad** [comment]
Yes, USM is coming to hipSYCL. Time scale is before the end of the year, likely earlier. Note that shared USM allocations are currently inefficient in HIP due to lack of page migration, but this is probably going to change with the hardware that's planned for Frontier (?).

**Comment by paboyle** [comment]
Brilliant news. Will close issue and watch 155.
