### ISSUE TITLE
spack installation atomic functions

### ISSUE THREAD

**Issue by arkantos493** [illuhad/hipSYCL#254]
I installed hipSYCL using spack (0.14.2-691-950180ab0) with the command `spack install hipsycl@master%gcc@8.4.0 build_type=RelWithDebInfo cuda=True ^gettext@0.19.8.1`.

This sets the "default-cpu-cxx" to "/usr/bin/g++-8" (which uses libstdc++). This leads to a problem with the atomic functions used on the cpu.

Example:
```cpp
#include <vector>
#include <iostream>
#include <numeric>

#include <CL/sycl.hpp>

namespace sycl = cl::sycl;

int main() {
    std::vector<int> before(10);
    std::iota(before.begin(), before.end(), 1);
    std::vector<int> after(10, 0);

    // print buffer BEFORE kernel call
    for (int i : before) {
        std::cout << i << " ";
    }
    std::cout << std::endl;
    for (int i : after) {
        std::cout << i << " ";
    }
    std::cout << std::endl << std::endl;    

    {
        sycl::queue queue(sycl::default_selector{});
        
        sycl::buffer<int, 1> buffer_before(before.data(), before.size());
        sycl::buffer<int, 1> buffer_after(after.data(), after.size());

        queue.submit([&](sycl::handler& cgh) {
            auto acc_before = buffer_before.get_access<sycl::access::mode::atomic>(cgh);
            auto acc_after  = buffer_after.get_access<sycl::access::mode::discard_write>(cgh);
            
            cgh.parallel_for<class test_kernel>(sycl::range<>(before.size()), [=](sycl::item<> item) {
                const auto idx = item.get_linear_id();
                // acc_after[idx] = acc_before[idx]++;
                acc_after[idx] = acc_before[idx].fetch_add(1);
            });
        });
    }

    // print buffer AFTER kernel call
    for (int i : before) {
        std::cout << i << " ";
    }
    std::cout << std::endl;
    for (int i : after) {
        std::cout << i << " ";
    }
    std::cout << std::endl;    

    return 0;
}
```
## Expected result:
```
1 2 3 4 5 6 7 8 9 10 
0 0 0 0 0 0 0 0 0 0 

2 3 4 5 6 7 8 9 10 11 
1 2 3 4 5 6 7 8 9 10 
```
I can get this expected result if I explicitly specify the GPU as target using `--hipsycl-platform=cuda`. 
## Actual result:
```
1 2 3 4 5 6 7 8 9 10 
0 0 0 0 0 0 0 0 0 0 

2 3 4 5 6 7 8 9 10 11 
2 3 4 5 6 7 8 9 10 11 
```
However if I explicitly specify the CPU as target using `--hipsycl-platform=cpu` the result is wrong, i.e. `fetch_add(1)` **doesn't** return the value **before** the call to the atomic function (as specified in the SYCL standard).

The problem is that the builtin intrinsic function `__atomic_add_fetch` used in GCC's libstdc++ **doesn't** return the value before the function call. Instead it returns the value **after** the function call ([see](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html)).

**Comment by illuhad** [comment]
Thank you! I think we simply need to replace `__atomic_add_fetch` with `__atomic_fetch_add` which should have the correct behavior. This may also affect other atomic functions such as `fetch_sub`. Do you want to submit a PR?

**Comment by arkantos493** [comment]
I have created a pull request changing:
`__atomic_add_fetch` -> `__atomic_fetch_add`
`__atomic_sub_fetch` -> `__atomic_fetch_sub`
`__atomic_and_fetch` -> `__atomic_fetch_and`
`__atomic_or_fetch` -> `__atomic_fetch_or`
`__atomic_xor_fetch` -> `__atomic_fetch_xor`
