### ISSUE TITLE
Scoped Parallelism Extension

### ISSUE THREAD

**Issue by illuhad** [illuhad/hipSYCL#259]
I'm currently thinking about creating an extension for a new kernel invocation mechanism that addresses the same points as hierarchical parallelism but should be substantially easier to implement on all platforms supported by hipSYCL, and have less surprises (functionality or performance-wise) for users. For lack of a better word, let's call it scoped parallelism.

It follows the goals
* Be efficiently implementable on GPU and host
* Be relatively easy to implement, without additional compiler magic
* Be explicit to avoid performance surprises
* Be able to express the same algorithms as `nd_range` parallel for.

This is all still brainstorming, so feedback welcome.

Like hierarchical parallel for, scoped parallelism uses two nested scopes. However, it is not strictly hierarchical in the sense of hierarchical parallel for, and it also is different from `nd_range` parallel for.
The fundamental difference becomes clear if we look at the parallel iteration space inside a single work group. Let `N` be the size of the physical iteration space inside a group, i.e. the number of actual "threads" running, and `M` the the logical iteration space, i.e. the work group size requested by the user.
* In hierarchical, we go from 1 to either `N` or `M`, as we go from the outer scope to the `parallel_for_work_item` scope.
* In `nd_range` parallel for, there's only one scope and `N=M`. The fact that N has to equal M in `nd_range`, without freedom for the implementation to choose `N`, is what makes it inefficient when implemented on the host.
* In scoped parallelism, we go from `N` to `M`. In other words, we launch the work group with as many physical "threads" as the implementation wants for best performance, and then distribute the `M` user-requested work items across the parallel threads.

Within a work group, scoped parallelism is similar to OpenMP's notion of first spawning a parallel region with some number of threads that is (by default) implementation-controlled using `#pragma omp parallel`, and then later distributing `M` iterations of a loop across the threads using `#pragma omp for`.

Scoped parallelism provides mechanisms to query both the position within the physical iteration space of size `N`, and the logical iteration space of size `M`. It also exposes subgroups to the programmer.

Example with more explanation:
```c++
constexpr size_t Group_size = 128;
q.submit([&](sycl::handler& cgh){
  auto data_accessor = ...;
  cgh.parallel<class Kernel>(sycl::range<1>{num_groups}, sycl::range<1>{Group_size}, 
  [=](sycl::group<1> grp, sycl::physical_item<1> phys_idx){
     // Inside the parallel scope, the degree of parallelism is implementation-defined
     // the implementation can use whatever is most efficient for hardware/backend.
     // In hipSYCL CPU, this would be executed by a single thread on CPU
     // and Group_size threads on hipSYCL GPU
     // phys_idx contains information about the position in the (implementation-defined)
     // physical iteration space

     // Local memory in parallel scope must be allocated explicitly as such
     sycl::local_memory<int [Group_size]> scratch{grp};
     // Same goes for private_memory, if required (here only dummy example)
     sycl::private_memory<int> dummy{grp};
     // Variables not explicitly marked as either can be declared as well under certain
     // circumstances, see the for loop below.

     // `distribute_for` distributes the logical, user-provided iteration space across the physical one. 
     // We might also support flexible group sizes in the future like for hierarchical parallelism..
     grp.distribute_for([&](sycl::subgroup<1> sg, sycl::logical_item<1> idx){
        scratch[idx.get_local_id(0)] = data_accessor[idx.get_global_id(0)];
        // Can execute code for a single item of the subgroup:
        sg.single_item([&](){
          ...
        });
     }); // implicit barrier at the end by default (mechanism to alter that behavior might also come)

     // Variables inside the parallel scope that are not explicitly local or private memory
     // are allowed, if they are not modified from inside `distribute_for()` scope.
     // The SYCL implementation will allocate those in private memory of the physical thread,
     // so they will always be efficient. This implies that the user should not attempt to assign values
     // per logical work item, since they are allocated per physical item.
     for(int i = Group_size / 2; i > 0; i /= 2){
       grp.distribute_for([&](sycl::subgroup<1> sg, sycl::logical_item<1> idx){
         size_t lid = idx.get_local_id(0);
         if(lid < i)
           scratch[lid] += scratch[lid+i];
       });
     }
     
     grp.single_item([&](){
       data_accessor[grp.get_group_id(0)] = scratch[0];
     }); //should this synchronize at the end?
  });
});
```

CC @tomdeakin
*EDIT0*: Rename `single_thread()` -> `single_item()`

*EDIT1*: A good way to think about this approach might be OpenMP, where the threads are first spawned with `#pragma omp parallel`, and the items to be processed in parallel are then distributed across the threads with `#pragma omp for`. A similar thing happens here: In the outer scope, all threads are spawned (based on whatever the amount of threads is that the SYCL implementation wants for best performance), and then the work items are distributed across the threads using `distribute_for()`.

*EDIT2*: Renamed `parallel_for`->`distribute_for`, introduced subgroups

*EDIT3*: Expanded introduction

*EDIT4*: Changed allocation rules for variables in outer scope without explicit local or private declarations: Variables inside the parallel scope that are not explicitly local or private memory are allowed, if they are not modified from inside `distribute_for()` scope. The SYCL implementation will allocate those in private memory of the physical thread, so they will always be efficient. This implies that the user should not attempt to assign values per logical work item, since they are allocated per physical item.

**Comment by keryell** [comment]
What is a thread?
`grp.single_thread([&](){`→`grp.single([&]{` or `grp.single_work_item([&]{`?

**Comment by tomdeakin** [comment]
Really interesting and thanks for sharing. I like the explicit memory space declarations but it might be cumbersome if you had a lot of private variables.

Are we allowed to nest `parallel_for`? Having multiple levels of nesting could be useful, especially if we don't specify a mapping. OpenMP exposes 3 levels: teams, threads and simd. What's tricky is it's a different word for each level. Also the sharing of an iteration space has a different word depending on the level too: distribute between teams, for between threads. simd has different semantics!

**Comment by illuhad** [comment]
> What is a thread?
grp.single_thread([&](){→grp.single([&]{ or grp.single_work_item([&]{?

Hehe.. you are right of course, thank you :) Maybe `single_item` would also be an option to retain the precision of `single_work_item` without being too long.

> Really interesting and thanks for sharing. I like the explicit memory space declarations but it might be cumbersome if you had a lot of private variables.

Maybe, but it's no worse than current hierarchical parallelism where private memory also has to be declared explicitly in the outer scope. For most code patterns, I would not expect a large number of local memory allocations, so I'm not really worried about too much `local_memory`. In order to be implementable on the host device, I really so no way around explicit `private_memory` if we want to allow the user to declare private memory in the outer scope.

The main problem is that on CPU, we want to have 1 thread per group with a loop across work items. So the outer scope will be executed by a single thread. If we now want to allocate some memory here for the work items (i.e. individual iterations of, effectively, a for loop), we actually need to allocate an array with one element per iteration. If we want to allow SYCL-as-a-library implementations on CPU, we need special constructs for private memory allocations for this.

Of course, inside `parallel_for` any declaration is private, so no additional effort required here. And as I mentioned, you can omit the `private_memory`/`local_memory` in the outer scope if you know that they're going to be the same for all work items (e.g. for constants). I think this will cover many cases in practice..

> Are we allowed to nest `parallel_for`?

Good question. The `teams` level would probably be covered by different work groups in our case. We already have this covered since each `parallel_scope` kernel starts with a `group` object. Since we are not really doing any hierarchical parallelism, I think we could easily expose SIMD parallelism exactly the same way as DPC++ does with subgroups for `nd_range` kernels, which would have the advantage for users that they don't have to learn something new and can just use it the same way they have don for `nd_range`. Perhaps there's also a better way to express this in this case, but this requires more investigation. So initially, I don't think that there will be any nesting, but I think this could be done in the future.

Maybe what happens might also be clearer if we don't call it `parallel_for` but `distribute_for` or something like that..

**Comment by tomdeakin** [comment]
Subgroups would be the framework to work with for this. But as we're doing hierarchical parallelism it could make more sense to express them as another parallel loop with a different iterator, instead of the kernel style programming required for the DPC++ subgroups:

This rough sketch shows what I'm thinking at:
```cpp
constexpr size_t Group_size = 128;
q.submit([&](sycl::handler& cgh){
  auto data_accessor = ...;
  cgh.parallel_scope<class Kernel>(sycl::range<1>{num_groups}, sycl::range<1>{Group_size}, 
  [=](sycl::group<1> grp) {
    // Level 1
    // Describes what each work-group is doing
    // Question? Is this executed by each work-item in the work-group or by a single work-item??

    grp.parallel_for([&](sycl::sg_item<1> sg) {
      // Level 2
      // Describes what each sub-group is doing

      sg.parallel_for([&](sycl::h_item<1> idx) {
      // Level 3
      // Describes what each work-item of the sub-group is doing
      });
    });
  });
});
```

> Maybe what happens might also be clearer if we don't call it `parallel_for` but `distribute_for` or something like that..

I think the trouble with having both `distribute_for` and `parallel_for` is that they need to do different things and parallelise over different levels in the hierarchy. It might be nicer to simply have `parallel_for` that parallelises over the next level down as above. Then it is flexible what the implementation maps each level to.

**Comment by illuhad** [comment]
Hm.. So, to be clear, this scoped parallelism concept is not really hierarchical, strictly speaking. In order to avoid all the issues associated with hierarchical, a fundamental aspect of it is that *all threads required by the backend for best performance are there right from the beginning*. This gives implementations the flexibility to do the right thing for performance.
So, the answer to your question of whether level 1 code is per group or per work item is: It depends. The degree of parallelism you have here is implementation (or backend) defined. I am worried that, if we introduce nested `parallel_for` we end up with exactly the same issues as in hierarchical. E.g. what happens if a variable declared in subgroup scope is used in the work item scope?
The implementation of this would probably also require a lot of compiler support, just like hierarchical...

What we could have quite easily though is probably something like:
```c++
grp.parallel_for([&](sycl::subgroup<1> sg, sycl::h_item<1> idx){
   sg.single_item([&](){
      // Executed once per subgroup
   });
   // Executed for each item
});
grp.single_item([&](){
   // Executed once per work group
}
```
This better matches the concept of "all threads are there from the beginning", I think. But I see that there is still some asymmetry here as we start from the `group` object, and then get both `h_item` and `subgroup` at the same time..

**Comment by illuhad** [comment]
... I think we could resolve the asymmetry by having:
```c++
cgh.parallel_scope<class Kernel>(..., 
  [=](sycl::group<1>, sycl::physical_item<1> phys){
  // The physical item contains information about the actual degree of parallelism that
  // the implementation uses
  grp.parallel_for([&](sycl::subgroup<1> sg, sycl::logical_item<1> logical_idx){
    // logical_item describes where we are in the user-specified iteration space.
    // On GPU, logical_idx = phys, on CPU the physical index is always 0 while
    // the logical item contains information about the actual position in the iteration space
    sg.single_item([&](){
      // Executed once per subgroup
   });
   // Executed for each item
  });
  grp.single_item([&](){
    // Executed once per work group
  });
});
```

**Comment by tomdeakin** [comment]
> Hm.. So, to be clear, this scoped parallelism concept is not really hierarchical, strictly speaking. In order to avoid all the issues associated with hierarchical, a fundamental aspect of it is that *all threads required by the backend for best performance are there right from the beginning.*

I think I missed that point, apologies. In that context your approach makes sense as an equivalent notation for `ndrange`.

**Comment by illuhad** [comment]
Updated the original post with subgroups, renamed `parallel_for` to `distribute_for`, renamed `parallel_scope` to `parallel`.

**Comment by illuhad** [comment]
> I think I missed that point, apologies. In that context your approach makes sense as an equivalent notation for ndrange.

@tomdeakin It's equivalent to ndrange in the sense that you can express the same algorithms with it, just like hierarchical is equivalent in that sense... But this form of parallelism distinguishes itself from ndrange by

* being performance portable between host and device
* having a clear separation between the user-provided logical iteration space and the actual parallelism employed by the implementation, giving the implementation the freedom to do things the optimal way. E.g. we could also support flexible work group ranges in scoped parallelism, just like in hierarchical parallel for.
* being a modern, less low-level way to express kernels 

I think there are aspects it has in common with ndrange, and some aspects it has in common with hierarchical. The best of both worlds, hopefully ;)

**Comment by illuhad** [comment]
Closing because feature is implemented.
