### ISSUE TITLE
HIPSYCL_PLATFORM not settable in CMakeLists.txt

### ISSUE THREAD

**Issue by lfield** [illuhad/hipSYCL#275]
Setting `-DHIPSYCL_PLATFORM=cpu` on the command line works fine but using `set(HIPSYCL_PLATFORM "cpu")` in the CMakeLists.txt file gives the following error:
```CMake Error at /opt/hipSYCL/lib/cmake/CMakeSYCLInformation.cmake:53 (message):
  More than one hipSYCL target platform is available.

  Please specify HIPSYCL_PLATFORM=cpu|cuda|rocm
Call Stack (most recent call first):
  /opt/hipSYCL/lib/cmake/hipsycl-config.cmake:9 (enable_language)
  CMakeLists.txt:15 (find_package)
```
I could reproduce this issue using the [example](https://github.com/illuhad/hipSYCL/blob/master/doc/examples.md) from the docs. If required, I can provide the CMakeLists.txt used.

**Comment by aTom3333** [comment]
Make sure to set the platform before calling `find_package(hypsycl)`

**Comment by aTom3333** [comment]
More information on that. It seems that the first time running cmake the `set` is ignored but taken into account the following times (potentially leading to surprising results, see #297 )
