### ISSUE TITLE
Conflict for hipsycl::sycl::detail::host_local_memory::_static_local_mem in libhipSYCL_cuda and libhipSYCL_cpu

### ISSUE THREAD

**Issue by aTom3333** [illuhad/hipSYCL#297]
When compiling for the CUDA platform I get a linker error complaining that the symbol `hipsycl::sycl::detail::host_local_memory::_static_local_mem` is defined both in libhipSYCL_cuda and libhipSYCL_cpu, once in TLS and once not in TLS.
The full linker error is:
```
/usr/bin/ld: _ZN7hipsycl4sycl6detail17host_local_memory17_static_local_memE: TLS definition in /path/to/hipsycl/install/bin/../lib//libhipSYCL_cpu.so section .tbss mismatches non-TLS definition in /path/to/hipsycl/install/lib/libhipSYCL_cuda.so section .bss
/usr/bin/ld: /path/to/hipsycl/install/bin/../lib//libhipSYCL_cpu.so: error adding symbols: bad value
```

Maybe I messed up somewhere, I find it strange that both libhipSYCL_cuda and libhipSYCL_cpu are linked. Here is my `CMakeLists.txt`:
```cmake_minimum_required(VERSION 3.16)
project(hipsycl_tls_issue)

set(HIPSYCL_PLATFORM cuda)
set(HIPSYCL_GPU_ARCH sm_52)
find_package(hipsycl CONFIG PATHS /home/thomas/Programmes/hipSYCL-install/lib/cmake/)

add_executable(hipsycl_tls_issue main.cpp)
add_sycl_to_target(
    TARGET hipsycl_tls_issue
    SOURCES main.cpp
)
```

And my source file to be exhaustive but that's a simple test program:
```
#include <iostream>
#include <CL/sycl.hpp>

using namespace cl::sycl;
int main()
{
    float a[] = {1.0, 2.0, 3.0, 4.0};
    float b[] = {1.0, -1.0, 1.0, -1.0};
    float out[4];
    unsigned int n = 4;
    
    queue q;
    {
        buffer<float> aBuf(a, n);
        buffer<float> bBuf(b, n);
        buffer<float> outBuf(out, n);
        q.submit([&](handler& h)
                 {
                     auto aAcc = aBuf.get_access<access::mode::read>(h);
                     auto bAcc = bBuf.get_access<access::mode::read>(h);
                     auto outAcc = outBuf.get_access<access::mode::write>(h);
                     h.parallel_for<class sycl_kernel>(range<1>(n), [=](id<1> id)
                     {
                         outAcc[id] = aAcc[id] + bAcc[id];
                     });
                 });
    }

    for(float x : out)
        std::cout << x << ' ';
}
```

**Comment by illuhad** [comment]
You are right with your suspicion - `libhipSYCL_cuda` and `libhipSYCL_cpu` should never be linked at the same time. I have seen something similar sometimes when switching `HIPSYCL_PLATFORM` with cmake. Apparently sometimes stuff is stuck in the cmake cache. Try cleaning your build directory and reconfiguring with cmake for your target platform.

**Comment by aTom3333** [comment]
Indeed, it fixes the problem. But I have the same problem as #275 the first time i run cmake, the `HIPSYCL_PLATFORM` isn't taken into account and causes the problem in the cmake cache, but when i ran cmake again without clearing the cache, it was working fine so i thought it was alright.
After clearing everything and calling `cmake` with `-DHIPSYCL_PLATFORM=cuda` everything works
