### ISSUE TITLE
[Extension] custom kernel launch mechanism for more efficient backend interoperability

### ISSUE THREAD

**Issue by illuhad** [illuhad/hipSYCL#306]
SYCL 2020 includes host tasks that can be used for interoperability with backends such as CUDA by allowing calls to native backend functions inside them. This may however not be optimal for performance if the the host task submits kernels because it is executed during DAG execution. 

If a host task is used to submit a custom backend kernel, or calls a backend library that submits kernels, this means that control flow would go from the GPU back to the CPU to execute the host task where another kernel is submitted, which would then execute again on the GPU.

Of course the extra trip to the CPU can cost performance as it adds latency *within DAG execution*. The solution would be to have such interop tasks execute at *DAG submission*, similar to how regular SYCL kernels are launched. This could look something like this:

```c++

q.submit([&](sycl::handler& cgh){
  cgh.custom_launch([=](/*some way to obtain backend objects, e.g. interop_handle*/){
    // This will be executed when the scheduler submits tasks.
    // This task will be synchronized within the DAG using device synchronization mechanisms,
    // instead of hos
  });
});

```

**Comment by keryell** [comment]
In SYCL you can use interoperability without a host task, if you do not want host interaction. Just using a normal `parallel_for` or `single_task`with a `kernel` and `buffer` that can be constructed with the interoperability API.
If the runtime is well designed, the DAG should be lowered into some back-end stuff when possible. Not done yet in triSYCL with the OpenCL backend...

**Comment by illuhad** [comment]
Sure you can have interoperability without host task but I don't see how this would solve the situation where you want to still integrate with the DAG. Let's say you want to call a cuBLAS function (and have dependencies for that) and other SYCL kernels that should depend on the cuBLAS kernel. How would you submit the cuBLAS function without relying on extra synchronization between host and device?

What I'm proposing is a mechanism that accomplishes that by letting you execute your interop code during the DAG submission process. This means you can just append your kernels to the backend queue (or whatever mechanism the backend uses), and the SYCL runtime will append other SYCL operations afterwards, requiring no synchronization between host and device, and minimal synchronization on device.

**Comment by keryell** [comment]
I still cannot see why it cannot be integrated in the DAG today with the current interoperability support in SYCL.
I am thinking to something like this: https://github.com/triSYCL/triSYCL/blob/master/tests/SDAccel/opencl_kernel_vector_add_args.cpp

**Comment by illuhad** [comment]
I'm not sure if it would be possible to use a `kernel` object to encapsulate the custom operation as your example does. I'm looking in particular at the case where we want to have interoperability with backend libraries (e.g, performing a cuBLAS operation). In that case we only know that cuBLAS will submit one or multiple operations, but we know no further details about them. Not even if they are kernels or other operations like synchronizations or data copies. I'm not sure the `kernel` interface would give us that much generality.

Another approach might be to use the interoperability API to access the backend queue and then submit directly to it. However this cannot work in hipSYCL because in hipSYCL a SYCL queue has no relation to a backend object. The runtime instead maintains a pool of backend queues (e.g. CUDA/HIP streams) and the scheduler automatically distributes incoming work across them. This has the advantage that we can get the same overlap of compute/data transfers or concurrent kernel execution no matter how many SYCL queues you use - even if you have only one.
This approach implies that we need to go through the scheduler to pick a backend queue for us, which we can then access. This is what happens in this extension.

**Comment by keryell** [comment]
OK, thanks for the explanation. You are right, the current interoperability API of SYCL 1.2.1 works well only when there is only a single kernel.
