### ISSUE TITLE
building throws: syclcc fatal error: hipSYCL platform has been specified multiple times

### ISSUE THREAD

**Issue by KestutisMa** [illuhad/hipSYCL#43]
.../hipsycl-cuda-git/src/hipSYCL/src/hipsycl_rewrite_includes/InclusionRewriter.cpp
syclcc fatal error: hipSYCL platform has been specified multiple times

Arch Linux, AUR package https://aur.archlinux.org/packages/hipsycl-cuda-git
that clones hipsycl-cuda-git 20190411.add57fc-1

**Comment by illuhad** [comment]
Thanks for reporting! The AUR PKGBUILD is outdated, I will fix it ASAP. To fix it, try removing the line `export HIPSYCL_PLATFORM=...` from the PKGBUILD. If you have CUDA installed, cmake should automatically enable the CUDA backend for you.

**Comment by illuhad** [comment]
Please try the PKGBUILD from PR #44

**Comment by KestutisMa** [comment]
Thanks for quick reply! `makepkg` was successful using PKGBUILD from #44 branch. Only thing: openmp should also be in dependencies list.

**Comment by illuhad** [comment]
Thanks, PR #44 is merged and OpenMP added as dependency. AUR PKGBUILD will be updated with the new PKGBUILD.
