### ISSUE TITLE
'syclcc --hipsycl-platform=nvidia' throws: usr/bin/ld: cannot find -lcudart_static

### ISSUE THREAD

**Issue by KestutisMa** [illuhad/hipSYCL#45]
```
[kest@archlinux gjSYCL]$ syclcc --hipsycl-platform=nvidia
/usr/bin/ld: cannot find -lcudart_static
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
[kest@archlinux gjSYCL]$
```
Tried `export LDFLAGS=-L/opt/cuda-9.2/lib64` also `LD_LIBRARY_PATH=/opt/hipSYCL/CUDA/lib64:/opt/cuda-9.2/lib64:`
Using PKGBUILD from #44

**Comment by illuhad** [comment]
does it also fail if you pass `-L/opt/cuda-9.2/lib64` directly to `syclcc`? Not sure why the environment variables are not taken into account.

**Comment by KestutisMa** [comment]
Yes, it does, tried more verbose output with -v:

[kest@archlinux gjSYCL]$ syclcc --hipsycl-platform=cuda -L/Lopt/cuda-9.2/lib64 -v
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/7.4.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.4.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/7.4.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/7.4.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /opt/cuda-9.2, version 9.2
 "/usr/bin/ld" -pie --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib64/Scrt1.o /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib64/crti.o /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/crtbeginS.o -L/opt/hipSYCL/CUDA/bin/../lib -L/Lopt/cuda-9.2/lib64 -L/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1 -L/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib64 -L/usr/bin/../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../.. -L/usr/bin/../lib -L/lib -L/usr/lib -lhipSYCL_cuda -lcudart_static -ldl -lrt -lstdc++ -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/crtendS.o /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib64/crtn.o
/usr/bin/ld: cannot find -lcudart_static
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
[kest@archlinux gjSYCL]$

**Comment by illuhad** [comment]
` -L/Lopt/cuda-9.2/lib64` -> typo?

**Comment by KestutisMa** [comment]
Indeed, there was typo, thanks for observation and sorry for that. It works with `syclcc -L/opt/cuda-9.2/lib64`. Using `export LDFLAGS=-L/opt/cuda-9.2/lib64` does not work.

**Comment by psalz** [comment]
You can also try using `export LIBRARY_PATH=<path>` (without the `LD_`, which is used by the dynamic linker)!

**Comment by KestutisMa** [comment]
Thank you @psalz, good point! it worked!
