### ISSUE TITLE
Potential hipSYCL related crash in Mandelbrot fractal viewer

### ISSUE THREAD

**Issue by illuhad** [illuhad/hipSYCL#47]
@VileLasagna, I'm moving the discussion here so that we don't clutter the cmake discussion :) I could not reproduce any crashes so far. Your SYCL code looks okay at first glance. However, I don't see a fractal - there's a black screen and if I click and drag the mouse, white rectangles are drawn on top. Is this expected (e.g. unfinished rendering code)?

EDIT: Nevermind - it seems that although the command group handler runs, the actual kernel is never running. This is likely a problem in hipSYCL.

**Comment by VileLasagna** [comment]
The white rectangle is a zoom selection area. Curious that it's not rendering for you, that is weird. Expected output is [like so] (https://photos.app.goo.gl/AR1uSjquvDULrZNo8)

And the error I get on subsequent runs is [this one](https://photos.app.goo.gl/7DZx9XmUwwqJEZfe9)

**Comment by illuhad** [comment]
Okay, the kernel invocation problem seems to be a clang issue - doesn't happen when using nvcc. It's now working for me, without crashes.
Can you please try commenting out the lines causing the assertion failure. I've just checked the code and I'm skeptical if that assertion statement is actually correct.

**Comment by VileLasagna** [comment]
I'll give it a go tonight. I was remoting in from work but it seems my home PC has either crashed or was turned off somehow.

**Comment by psalz** [comment]
Without having tested it myself, this

>the kernel invocation problem seems to be a clang issue

sounds a lot like the weird compiler bugs I'd previously run into while trying to get Catch2 to compile with Clang. Try running it through `cuda-memcheck` - is the error something like `invalid call to cudaLaunch`? I actually wanted to find a small reproducible case of this for #42 today.

**Comment by VileLasagna** [comment]
Hello @illuhad I've tried commenting out that assertion and sure enough, I seem unable to reproduce the crash now, so it seems you were on the money. Looks like I've got a working SYCL thingie for now =P

With that being the case, do you think there's still value in getting the crash back and trying to push it through cuda-memcheck, @psalz? I can try and get to it later this week but I'll need to massage my build into working for either CUDA or NVCC.

**Comment by psalz** [comment]
If you know that the kernel actually executes now it's fine, but as far as I can remember the problem with the Clang bug is that it fails silently, only `cuda-memcheck` will report the issue.

@illuhad do you mean that the assertion statement isn't correct in this particular case or in general? Because I've also sporadically been running into this assertion but never had time to really pin down why or when it happens exactly.

**Comment by illuhad** [comment]
Actually, I'm not sure. In order to find out what buffers an accessor belong to, we have the `accessor_tracker` which maps memory addresses of accessors to buffer objects. We use the memory addresses directly to avoid bloating the accessor (which will be copied to device, so better to avoid unnecessary attributes). In the constructor, destructor, assignment operator of accessors we update the map in the `accessor_tracker` object.

This particular assertion makes sure that, when a new accessor wants to put itself into the map, an entry for this accessor memory address doesn't exist yet. In itself, that would be wrong since of course a different accessor can be put in the same memory location later on. However, we also remove accessors again in their destructor. So, in principle, before a new accessor comes in at the same memory address, the previous should have invoked its destructor and hence be removed from the address.
I suspect that this assumption does not hold entirely because of multithreading issues or some compiler optimization (e.g. if the compiler realizes that during the destructor `accessor` actually doesn't have to access its own memory). But so far I cannot pinpoint the problem exactly either.

**Comment by illuhad** [comment]
@psalz, `cuda-memcheck` reveals the following problem when compiling with clang:
```
========= Program hit cudaErrorNoKernelImageForDevice (error 48) due to "no kernel image is available for execution on the device" on CUDA API call to cudaLaunch. 

```
It seems to me that clang, for whatever reason, has failed to embed the kernel into the binary.

**Comment by illuhad** [comment]
Closing in on the real problem: It seems that for each submit, there occurs always one call less to accessor destructors than calls to constructors. This causes two rather significant problems:
* If later on another accessor is constructed in the same memory location, the assertion will be triggered. This is the problem @VileLasagna noticed.
* Even worse, we have a humongous memory leak, since we keep entries for dead accessors in the map, which each store a `buffer_ptr` (i.e., `shared_ptr` to buffers). Memory of these buffers will never actually be released, since the reference count of the `shared_ptr` can never go to 0.

Originally I thought that the problem may be caused by us moving lambdas to the device so that the destructor is actually invoked on the device instead of the host. This has turned out not to be the case since the CPU backend exhibits the same behavior. So, we have to go memory leak debugging ;)

**Comment by illuhad** [comment]
@VileLasagna, could you please check if the problem can still be reproduced with PR #53?

**Comment by VileLasagna** [comment]
Sadly, still got it. One curious thing, though, is that it now seems to always happen on the third generation (initial draw works fine, second works fine apparently 100% of the time, third seems to always crash). I build hipSYCL with debug info 3. I'm posting my output to see if it gives you some light. I'm using hipsycl_rocm, will try and reproduce with other backends:

```
Running on Vega 10 XL/XT [Radeon RX Vega 56/64]
[hipSYCL Info] buffer_state_info: host access, current data versions: host-side is @0, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @0)
[hipSYCL Info] buffer_state_info: host access, current data versions: host-side is @0, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @0)
[hipSYCL Info] task_graph: Receiving task node 0x1dbe150
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] task_graph: Receiving task node 0x1dc0a20
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] task_graph:    0x1dbe150
[hipSYCL Info] task_graph: Submitting node 0x1dbe150
[hipSYCL Info] buffer_state_info: device access, current data versions: host-side is @1, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @2)
[hipSYCL Info] buffer_impl: Executing async Host->Device copy of size 3686400
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 1
[hipSYCL Info] task_graph: node 0x1dbe150 has completed
[hipSYCL Info] task_graph: Submitting node 0x1dc0a20
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 1
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] task_graph: node 0x1dc0a20 has completed
[hipSYCL Info] buffer_cleanup_trigger: Buffer went out of scope, triggering cleanup
[hipSYCL Info] buffer_impl: Preparing write-back
[hipSYCL Info] task_graph: Receiving task node 0x1dbcfe0
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] task_graph: Submitting node 0x1dbcfe0
[hipSYCL Info] buffer_impl: Skipping write-back, device memory and write-back memory are already in sync.
[hipSYCL Info] task_graph: node 0x1dbcfe0 has completed
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 1
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] buffer_cleanup_trigger: Buffer went out of scope, triggering cleanup
[hipSYCL Info] buffer_impl: Preparing write-back
[hipSYCL Info] task_graph: Receiving task node 0x1dbdef0
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] task_graph:    0x1dbe150
[hipSYCL Info] task_graph:    0x1dc0a20
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] task_graph: Submitting node 0x1dbdef0
[hipSYCL Info] buffer_impl: Executing async Device->Host copy for writeback to host buffer
[hipSYCL Info] task_graph: node 0x1dbdef0 has completed
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] buffer_state_info: host access, current data versions: host-side is @0, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @0)
[hipSYCL Info] buffer_state_info: host access, current data versions: host-side is @0, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @0)
[hipSYCL Info] task_graph: Receiving task node 0x1e8b9d0
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] task_graph: Receiving task node 0x1e827e0
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] task_graph:    0x1e8b9d0
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] task_graph: Submitting node 0x1e8b9d0
[hipSYCL Info] buffer_state_info: device access, current data versions: host-side is @1, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @2)
[hipSYCL Info] buffer_impl: Executing async Host->Device copy of size 3686400
[hipSYCL Info] task_graph: node 0x1e8b9d0 has completed
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] task_graph: Submitting node 0x1e827e0
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] task_graph: node 0x1e827e0 has completed
[hipSYCL Info] buffer_cleanup_trigger: Buffer went out of scope, triggering cleanup
[hipSYCL Info] buffer_impl: Preparing write-back
[hipSYCL Info] task_graph: Receiving task node 0x1e8b680
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 1
[hipSYCL Info] task_graph: Submitting node 0x1e8b680
[hipSYCL Info] buffer_impl: Skipping write-back, device memory and write-back memory are already in sync.
[hipSYCL Info] task_graph: node 0x1e8b680 has completed
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 1
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] buffer_cleanup_trigger: Buffer went out of scope, triggering cleanup
[hipSYCL Info] buffer_impl: Preparing write-back
[hipSYCL Info] task_graph: Receiving task node 0x1dca9f0
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] task_graph:    0x1e8b9d0
[hipSYCL Info] task_graph:    0x1e827e0
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] task_graph: Submitting node 0x1dca9f0
[hipSYCL Info] buffer_impl: Executing async Device->Host copy for writeback to host buffer
[hipSYCL Info] task_graph: node 0x1dca9f0 has completed
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] buffer_state_info: host access, current data versions: host-side is @0, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @0)
[hipSYCL Info] buffer_state_info: host access, current data versions: host-side is @0, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @0)
[hipSYCL Info] task_graph: Receiving task node 0x1e4b1b0
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] task_graph: Receiving task node 0x1dbe7e0
[hipSYCL Info] task_graph:  Dependencies: 
[hipSYCL Info] task_graph:    0x1e4b1b0
[hipSYCL Info] task_graph: Submitting node 0x1e4b1b0
[hipSYCL Info] buffer_state_info: device access, current data versions: host-side is @1, device side is @0
[hipSYCL Info] buffer_state_info: (new state: host @1, device @2)
[hipSYCL Info] buffer_impl: Executing async Host->Device copy of size 3686400
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 1
[hipSYCL Info] task_graph: node 0x1e4b1b0 has completed
[hipSYCL Info] Async worker thread: Processing op, remaining queue size: 0
[hipSYCL Info] task_graph: Submitting node 0x1dbe7e0
tbSYCL: /opt/hipsycl/bin/../include/CL/sycl/detail/runtime.hpp:58: void cl::sycl::detail::accessor_tracker::new_accessor(const cl::sycl::detail::accessor_base *, cl::sycl::detail::buffer_ptr): Assertion `_buffer_map.find(object_ptr) == _buffer_map.end()' failed.
Aborted (core dumped)
```

**Comment by illuhad** [comment]
hm, I'm not sure what to make of that. Could you please add the following diagnostics to the `accessor_tracker` in `detail/runtime.hpp` and rerun:

```cpp
 void new_accessor(
      const accessor_base* accessor_ptr,
      buffer_ptr buff)
  {
    std::lock_guard<mutex_class> lock{_lock};
    // ADD HERE:
   HIPSYCL_DEBUG_INFO << "accessor_tracker: Creating new entry for accessor @"
       << accessor_ptr << " for buffer @" << buff.get() << std::endl;
    const void* object_ptr = reinterpret_cast<const void*>(accessor_ptr);
    assert(_buffer_map.find(object_ptr) ==
           _buffer_map.end());

    _buffer_map[object_ptr] = buff;
  }

  void set_accessor_buffer(
      const accessor_base* accessor_ptr,
      buffer_ptr buff)
  {
    std::lock_guard<mutex_class> lock{_lock};
    // ADD HERE:
    HIPSYCL_DEBUG_INFO << "accessor_tracker: Resetting entry for accessor @"
       << accessor_ptr << " to buffer @" << buff.get() << std::endl;
    const void* object_ptr = reinterpret_cast<const void*>(accessor_ptr);
    assert(_buffer_map.find(object_ptr) !=
           _buffer_map.end());

    _buffer_map[object_ptr] = buff;
  }

  void release_accessor(
      const accessor_base* accessor_ptr)
  {
    std::lock_guard<mutex_class> lock{_lock};
    // ADD HERE:
   HIPSYCL_DEBUG_INFO << "accessor_tracker: Deleting entry for accessor @"
       << accessor_ptr << std::endl;
    const void* object_ptr = reinterpret_cast<const void*>(accessor_ptr);
    assert(_buffer_map.find(object_ptr) !=
           _buffer_map.end());

    _buffer_map.erase(object_ptr);
  }

  // Also add new member function:
  void dump()
  {
    HIPSYCL_DEBUG_INFO << " ******************* accessor_tracker dump ***********************" << std::endl;
    for(auto entries : _buffer_map)
      HIPSYCL_DEBUG_INFO << entires.first << " -> " << entries.second.get() << std::endl;
  }
```
And then also call `cl::sycl::detail::application::get_hipsycl_runtime().get_accessor_tracker().dump()` after / before each kernel call.

**Comment by VileLasagna** [comment]
Hey there

So I just did the thing, on top of current master and I was unable to get it to crash so.. whether I had some garbage version leftover, or it was indeed fixed or it was something underlying in drivers, the issue seems to be gone now, at the very least building for ROCm (I didn't yet get around to sorting out builds for other backends)

**Comment by illuhad** [comment]
okay, that's great to hear! Let's hope it's not some partially non-deterministic bug that just decided to go away only to come again a couple of days later ;)

If I don't hear anything new I will close the issue tomorrow. Please reopen if the issue appears again at some point.

**Comment by VileLasagna** [comment]
Can do, will keep an eye on it =P
