### ISSUE TITLE
clang compatibility question

### ISSUE THREAD

**Issue by acowley** [illuhad/hipSYCL#67]
I'm having trouble getting `syclcc-clang` to work on NixOS with [nixos-rocm](https://github.com/nixos-rocm/nixos-rocm), and realized I may be trying something known not to work.

The REAMDE says,

`In order to use the new clang-based toolchain, hipSYCL must be compiled against the same clang version used by ROCm (at the moment clang 9)`

and

`llvm/clang (with development headers and libraries). LLVM/clang 6, 7 and 8 are supported at the moment.`

Should I expect to be able to be able to get `clang-9` as used by ROCm 2.4 to work with `syclcc-clang`? I'm hitting issues with `amp` annotations in `hcc` headers, so this is entirely possibly something I'm  doing wrong with exposing hcc's clang, but I'd like to be sure ROCm 2.4 and clang-9 is a supported configuration.

**Comment by illuhad** [comment]
We should probably update that list and add clang 9 (while removing at least clang 6). clang 9 should work. However, if the HIP headers use the `amp` codepath, are you in fact perhaps using `hcc`?

You need what AMD calls "hip-clang", i.e. 
* https://github.com/RadeonOpenCompute/clang (`amd-common` branch)
* https://github.com/RadeonOpenCompute/llvm (`amd-common` branch)
* https://github.com/RadeonOpenCompute/lld (`amd-common` branch)

I'm not familiar with the ROCm packages from NixOS, but at least in the official ROCm binary packages hip-clang is not available as far as I know and must be compiled from source. I'm aware that's inconvenient for users, but hopefully this will change once `hcc` is deprecated and removed from the ROCm distribution.

I have also had some limited success with vanilla clang 9 (e.g nightly packages from apt.llvm.org), which could compile all unit tests except for the `vec<>` API test.

I'm still kind of trying to see what configurations work best on ROCm for the clang plugin, so let me know if it works :) We should probably also update the readme to elaborate more on the clang requirements on ROCm.

**Comment by acowley** [comment]
I think I see the problem. I build hip with the hcc backend on NixOS (I’m the main contributor to the nixos-rocm packaging), so I was using that clang for hipSYCL as I misinterpreted what was meant by hip clang in the README here. I also have available the clang for rocm OpenCL, but I haven’t yet gone the hip-clang route as I wasn’t sure if it was ready for wider use yet. I’ll try that out, build hipSYCL with that clang, and report back. Thank you for the response!

**Comment by acowley** [comment]
I got `hip-clang` incorporated in the NixOS ROCm package set, but I'm still having problems with hipsycl getting tangled up with hcc. 

My understanding is that I still want the `rocm` platform, but the hipsycl build does quite a bit of checking to ensure that the deprecated `hcc` is available to enable the `rocm` platform. At the same time, ROCm's hcc should be built against the the `hcc-clang-upgrade` fork, which brings another clang toolchain into scope. If that clang is available, I end up with `syclcc-clang` trying to use hcc's clang, which fails. If `hcc` is not available to the `hipsycl` build, I don't get a `hipSYCL_rocm.so`, and the remaining `cpu` platform is missing `omp.h` for my build of that pathway.

Since `hcc` was deprecated a while back, I suppose this will all get simpler over the next few months. I'll try to find time to further gut the hcc checks to see if that un-sticks things.
