### ISSUE TITLE
multiple definitions of cl::sycl::program::get_kernel

### ISSUE THREAD

**Issue by reguly** [illuhad/hipSYCL#85]
With the latest master, when I am linking multiple files with SYCL kernels in them together, I am getting multiple definitions linker errors 

/home/ireguly/OP2-Common/op2/c/lib/libop2_sycl.a(op_sycl_rt_support.o): In function `~_Sp_counted_ptr_inplace':
/usr/local/bin/../include/CL/sycl/kernel.hpp:141: multiple definition of `cl::sycl::program::get_kernel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
/tmp/airfoil_kernels-31c8a3.o:airfoil_kernels.cpp:(.text+0x0): first defined here

This was not present with 46216fe

**Comment by illuhad** [comment]
Thanks for reporting! We should probably add a test case for linking several source files and catch such regressions. I'll fix ASAP.

**Comment by illuhad** [comment]
Could you please confirm if PR #86 fixes the issue?

**Comment by reguly** [comment]
Yes, that seems to have done the trick - thank you!
