### ISSUE TITLE
OpenCL interoperability for NVIDIA GPUs with pocl's cuda backend

### ISSUE THREAD

**Issue by illuhad** [illuhad/hipSYCL#9]
One of the major caveats of hipSYCL is that doesn't support the OpenCL interoperability layer required by the spec. This is because it doesn't build on OpenCL but on HIP/CUDA instead.
We could however have interoperability to pocl's cuda backend. This OpenCL implementation internally makes use of CUDA objects, with which hipSYCL could then interact.
We would then get OpenCL interoperability at least when using nvidia GPUs. It won't work with NVIDIA's official OpenCL implementation, but that implementation doesn't support SPIR and is hence a second-class citizen in the SYCL world anyway :)

**Comment by keryell** [comment]
SYCL 1.2.1 comes with the OpenCL interoperability but there is more and more interest for SYCL Next to have more optional features and more back-ends. SYCL is quite a generic programming model for heterogeneous computing, so the SYCL committee could increase the number of potential back-ends, each one with a generic interoperability mode similar to the OpenCL one. For example, if you make one for CUDA, it could be standardized as an optional one. :-)

**Comment by illuhad** [comment]
Thanks for the info! It would make it far easier for something like hipSYCL to approach standard conformance if OpenCL interoperability were optional (or replaced with hip interoperability), so I am highly interested in this direction of SYCL next. With this information, it seems I should expand and polish hipSYCL's HIP/CUDA interoperability as a test for a potentially standardized interoperability with a HIP/CUDA backend. Let me know if there's anything else I can do to help the SYCL committee move forward on this issue :)

**Comment by keryell** [comment]
A simple starting point is to look with your advisor whether your university can participate to Khronos Group... :-)

**Comment by illuhad** [comment]
There's certainly growing interest in my institute in officially supporting (hip)SYCL, but these things need time ;)

**Comment by illuhad** [comment]
(closing this for now, as improving CUDA/HIP interoperability seems like a better investment of time given the planned future of SYCL)
